### ISSUE TITLE
Panic when logged out

### ISSUE THREAD

**Issue by nogweii** [mattn/tailscale-systray#18]
When running `tailscale-systray` when the daemon is not running it appears as normal. Clicking "Connect" in the menu prompts me to start the daemon, so I ran `systemctl start tailscaled`. Once the daemon starts the systray program crashes.

Running it in the terminal:

```
$ tailscale-systray 
panic: runtime error: index out of range [0] with length 0

goroutine 23 [running]:
main.onReady.func4()
github.com/mattn/tailscale-systray/main.go:155 +0x885
created by main.onReady
github.com/mattn/tailscale-systray/main.go:121 +0x43d
```

Running `tailscale status` in the terminal:

<details>
<summary>Text output</summary>

```
Logged out
```

</details>

<details>
<summary>JSON output</summary>

```json
{
"Version": "1.20.4",
"BackendState": "NeedsLogin",
"AuthURL": "",
"TailscaleIPs": null,
"Self": {
"ID": "",
"PublicKey": "nodekey:0000000000000000000000000000000000000000000000000000000000000000",
"HostName": "local-machine",
"DNSName": "",
"OS": "linux",
"UserID": 0,
"TailscaleIPs": null,
"Addrs": [],
"CurAddr": "",
"Relay": "",
"RxBytes": 0,
"TxBytes": 0,
"Created": "0001-01-01T00:00:00Z",
"LastWrite": "0001-01-01T00:00:00Z",
"LastSeen": "0001-01-01T00:00:00Z",
"LastHandshake": "0001-01-01T00:00:00Z",
"Online": false,
"KeepAlive": false,
"ExitNode": false,
"ExitNodeOption": false,
"Active": false,
"PeerAPIURL": null,
"InNetworkMap": false,
"InMagicSock": false,
"InEngine": false
},
"Health": [
"state=NeedsLogin, wantRunning=false"
],
"MagicDNSSuffix": "",
"CertDomains": null,
"Peer": null,
"User": null
}
```

</details>

Seems like it doesn't handle when `.TailscaleIPs` is null.

### Versions

* Tailscale 1.20.4
* tailscale-systray on git 64347899f5c60ccc3a7c5ebfa193364b918a38ef
* KDE Plasma 5.24.1
* Arch Linux (with kernel 5.16.10-zen)

**Comment by nogweii** [comment]
After logging in using a terminal, the systray works just fine.

Not sure if it matters, but this is on a fresh machine, that had only just recently installed tailscale. Never logged in before.

**Comment by prabirshrestha** [comment]
Hit the same issue. Seems like it always expects there to be 1 ip address. When not signed it it will crash.

https://github.com/mattn/tailscale-systray/blob/8e943debe7801a79c0e146cf9f53f0b9aa9d5e72/main.go#L154-L156

**Comment by RahulSriram** [comment]
I had the same issue as mentioned here, I have opened a PR with a fix for it now

**Comment by nogweii** [comment]
Said PR fixes the issue. Hooray! (2 years later :laughing: )
